# ============================
# STEP 1 — BUILD JAR
# ============================
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copy backend project
COPY School-Management/pom.xml .
COPY School-Management/src ./src
COPY School-Management/mvnw .
COPY School-Management/mvnw.cmd .
COPY School-Management/.mvn ./.mvn

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

# ============================
# STEP 2 — RUN JAR
# ============================
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
