# ========== Build Stage ==========
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copy pom.xml and download dependencies (cache optimization)
COPY pom.xml .
RUN mvn -q dependency:go-offline

# Now copy the rest of the project
COPY src ./src

# Build jar
RUN mvn -q clean package -DskipTests

# ========== Run Stage ==========
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
